# Generated by Django 5.1.4 on 2024-12-15 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockExchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='priceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('openPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('highPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('lowPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('closePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('volumeTraded', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockExchange.company')),
            ],
        ),
    ]
